### ISSUE TITLE
IceNet hackathon @Turing

### ISSUE THREAD

**Issue by aldenc** [icenet-ai/icenet-project#40]
As we discussed at the last working group meeting, it would be great to get everyone together in person for a mini-hackathon at the Turing. Since a lot of people are traveling to London for AI UK, and we have the easter holidays in early April, I'd propose something in the second half of April.

@JimCircadian @EllieBowler @rchan26 @ots22 @tom-andersson @ampersandmcd @scotthosking please let me know which dates you are available
Thursday, April 20
Friday, April 21
Tuesday, April 25
Thursday, April 27
Friday, April 28

Also please tag anyone I may have missed!

**Comment by tom-andersson** [comment]
Thanks @aldenc !

April 19th-21st is the Climate Informatics conference that some of us are planning to attend, so I can't make the first two days. However, I can make all three days on the following week.

**Comment by aldenc** [comment]
ah well that's good to know! do you think the following week is ok or will you want a break after the conference? (of course I am in the states first week of May so we'd be pushing pretty far out 😆 )

**Comment by ots22** [comment]
21 - 28 April all work for me, thanks @aldenc.

**Comment by JimCircadian** [comment]
Week commencing 24th might work for me: as with Tom I might be at Climate Informatics depending on whether I'm presenting. 😉

**Comment by rchan26** [comment]
hey @aldenc - 21-28 April work for me too 🙂

**Comment by EllieBowler** [comment]
Hi @aldenc - 21-28th work for me too! Slight preference for 21st or 25th but can easily shuffle other things around. Thanks 🙂

**Comment by aldenc** [comment]
@JimCircadian @EllieBowler @rchan26 @ots22 @tom-andersson @ampersandmcd @scotthosking
ok let's eliminate the 20th/21st, and the only preference expressed is for the 25th, so that sounds good to me! Any objections? Did I miss anyone?

**Comment by aldenc** [comment]
I've sent out a calendar invite for the 25th - closing this issue now and we can circle back around the end of March/beginning of April to firm up the details

**Comment by ampersandmcd** [comment]
Hey all! Sorry for my late arrival to the party!

I’ll be busy 19-21 April helping run the [Climate Informatics Conference](https://cambridge-iccs.github.io/climate-informatics-2023/) here in Cambridge, then busy again 24-28 April attending and presenting at [EGU23](https://www.egu23.eu/) in Vienna.

Do feel free to go ahead on the hackathon without me and I’ll be happy to catch up on all the fun asynchronously!

Perhaps we can run another later in the summertime!
